import * as fs from 'fs';
import * as path from 'path';
import { DiffReport, ChangeEntry, ArchGuardConfig } from '../types/index';
import { resolveDir } from '../utils/config';

const SEVERITY_EMOJI: Record<string, string> = {
  breaking: '🔴',
  'non-breaking': '🟡',
  informational: '🟢',
};

const TYPE_EMOJI: Record<string, string> = {
  added: '➕',
  removed: '➖',
  modified: '🔄',
};

export function generateMarkdownReport(report: DiffReport, config: ArchGuardConfig): string {
  const lines: string[] = [];

  lines.push(`# 🛡 ArchGuard Diff Report`);
  lines.push(``);
  lines.push(`**Project:** ${report.projectName}`);
  lines.push(`**Generated:** ${new Date(report.generatedAt).toLocaleString()}`);
  lines.push(`**From:** \`${report.fromSnapshot}\``);
  lines.push(`**To:** \`${report.toSnapshot}\``);
  lines.push(``);
  lines.push(`## 📊 Summary`);
  lines.push(``);
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| 🔴 Breaking Changes | **${report.summary.breakingChanges}** |`);
  lines.push(`| Total Changes | ${report.summary.totalChanges} |`);
  lines.push(`| ➕ Added Endpoints | ${report.summary.addedEndpoints} |`);
  lines.push(`| ➖ Removed Endpoints | ${report.summary.removedEndpoints} |`);
  lines.push(`| 🔄 Modified Endpoints | ${report.summary.modifiedEndpoints} |`);
  lines.push(`| Added Schemas | ${report.summary.addedSchemas} |`);
  lines.push(`| Removed Schemas | ${report.summary.removedSchemas} |`);
  lines.push(`| Modified Schemas | ${report.summary.modifiedSchemas} |`);
  lines.push(``);

  if (report.summary.breakingChanges > 0) {
    lines.push(
      `> ⚠️ **WARNING:** This diff contains **${report.summary.breakingChanges} breaking change(s)** that require immediate Frontend attention.`
    );
    lines.push(``);
  }

  if (report.changes.length === 0) {
    lines.push(`## ✅ No Changes Detected`);
    lines.push(``);
    lines.push(`The API contract is identical between both snapshots.`);
    lines.push(``);
    return lines.join('\n');
  }

  const byCategory = groupBy(report.changes, 'category');

  const categoryOrder: ChangeEntry['category'][] = [
    'endpoint',
    'parameter',
    'request-body',
    'response',
    'schema',
    'info',
  ];

  const categoryTitles: Record<ChangeEntry['category'], string> = {
    endpoint: '🔌 Endpoint Changes',
    parameter: '🔧 Parameter Changes',
    'request-body': '📤 Request Body Changes',
    response: '📥 Response Changes',
    schema: '📐 Schema Changes',
    info: 'ℹ️ API Info Changes',
  };

  for (const category of categoryOrder) {
    const catChanges = byCategory[category];
    if (!catChanges || catChanges.length === 0) continue;

    lines.push(`## ${categoryTitles[category]}`);
    lines.push(``);

    for (const change of catChanges) {
      const sev = SEVERITY_EMOJI[change.severity];
      const typ = TYPE_EMOJI[change.type];
      const endpoint = change.method
        ? `\`${change.method} ${change.path}\``
        : `\`${change.path}\``;

      lines.push(`### ${typ} ${sev} ${endpoint}`);
      lines.push(``);
      lines.push(`**Severity:** ${change.severity.toUpperCase()}`);
      lines.push(`**Change:** ${change.description}`);
      lines.push(`**Frontend Impact:** ${change.frontendImpact}`);
      lines.push(``);

      if (change.before !== undefined || change.after !== undefined) {
        lines.push(`<details>`);
        lines.push(`<summary>📋 Before / After</summary>`);
        lines.push(``);

        if (change.before !== undefined) {
          lines.push(`**Before:**`);
          lines.push(`\`\`\`json`);
          lines.push(JSON.stringify(change.before, null, 2));
          lines.push(`\`\`\``);
          lines.push(``);
        }

        if (change.after !== undefined) {
          lines.push(`**After:**`);
          lines.push(`\`\`\`json`);
          lines.push(JSON.stringify(change.after, null, 2));
          lines.push(`\`\`\``);
        }

        lines.push(`</details>`);
        lines.push(``);
      }

      lines.push(`---`);
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`*Generated by [ArchGuard](https://github.com/archguard/cli) 🛡*`);
  lines.push(``);

  return lines.join('\n');
}

export function saveReport(markdown: string, report: DiffReport, config: ArchGuardConfig): string {
  const historyDir = resolveDir(config.historyPath);
  fs.mkdirSync(historyDir, { recursive: true });

  const filename = `diff-${report.fromVersion}-to-${report.toVersion}.md`;
  const filepath = path.join(historyDir, filename);
  const latestPath = path.join(historyDir, 'diff-latest.md');

  fs.writeFileSync(filepath, markdown);
  fs.writeFileSync(latestPath, markdown);

  updateHistoryIndex(historyDir, filename, report);

  return filepath;
}

function updateHistoryIndex(historyDir: string, filename: string, report: DiffReport): void {
  const indexPath = path.join(historyDir, 'INDEX.md');
  const header = `# 📚 ArchGuard History Index\n\n| Date | Report | Breaking | Total |\n|------|--------|----------|-------|\n`;

  let existing = '';
  if (fs.existsSync(indexPath)) {
    const content = fs.readFileSync(indexPath, 'utf-8');
    const lines = content.split('\n');
    const tableStart = lines.findIndex((l) => l.startsWith('|---'));
    if (tableStart !== -1) {
      existing = lines.slice(tableStart + 1).join('\n');
    }
  }

  const date = new Date(report.generatedAt).toLocaleDateString();
  const newRow = `| ${date} | [${filename}](./${filename}) | ${report.summary.breakingChanges} | ${report.summary.totalChanges} |\n`;

  fs.writeFileSync(indexPath, header + newRow + existing);
}

function groupBy<T>(arr: T[], key: keyof T): Record<string, T[]> {
  return arr.reduce(
    (acc, item) => {
      const k = String(item[key]);
      if (!acc[k]) acc[k] = [];
      acc[k].push(item);
      return acc;
    },
    {} as Record<string, T[]>
  );
}
